### PR TITLE
Add Apache license

### LINKED ISSUE #30: Choose a license
We need to https://choosealicense.com/ for this project. Once this is done we should provide a LICENSE file and update the README accordingly.

### PR DESCRIPTION
**Pull request by AnastasiaPromtep**
Closes #30 

I added and applied the Apache license to the project.

Unfortunately, it is recommended to add a block of the license to the beginning of all the source files.

### CODE REVIEW

**Comment by maximelouet** [comment]
I don't think we should add the license block to each file, it's only gonna be cumbersome for us. As we don't have strong intellectual property protection requirements I suggest we only include the LICENSE file at the root of the repository.

**Comment by AnastasiaPromtep** [comment]
I agree, I removed license header on each file.

**Comment by AnastasiaPromtep** [comment]
It seems that a node package is depending on those packages: python3 make gcc g++, which prevent our CI to build correctly.
I can update the Dockerfile to add those missing packages.

**Comment by maximelouet** [comment]
Fixed in #38

**Comment by maximelouet** [comment]
@AnastasiaPromtep feel free to `git rebase origin/develop` this branch, then `git push -f`, after pulling.

**Pull request merged**
